const blogData = [
  {
    id: 1,
    url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
    header: 'Understanding Your Weekly Horoscope',
    text: 'Discover how the planets influence your mood, decisions, and fate in this week’s horoscope breakdown.',
    category: 'Horoscope',
    author: 'Admin',
    likes: 1244,
    comments: 256,
    date: '2025-08-28',
    tags: ['News', 'Horoscope'],
  },
  {
    id: 2,
    url: 'https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?auto=format&fit=crop&w=800&q=80',
    header: '5 Ways to Find Inner Peace Through Meditation',
    text: 'Learn effective meditation techniques to help calm your mind and improve your overall wellbeing.',
    category: 'Wellness',
    author: 'Admin',
    likes: 874,
    comments: 145,
    date: '2025-08-25',
    tags: ['Wellness', 'Spiritual'],
  },
  {
    id: 3,
    url: 'https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?auto=format&fit=crop&w=800&q=80',
    header: 'Zodiac Signs Ranked by Intelligence',
    text: 'Do zodiac signs affect intelligence? We take a lighthearted look at the stars and brains.',
    category: 'Zodiac',
    author: 'Admin',
    likes: 1322,
    comments: 312,
    date: '2025-08-30',
    tags: ['Fun', 'Astrology'],
  },
  {
    id: 4,
    url: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=800&q=80',
    header: 'How the Full Moon Affects Your Emotions',
    text: 'Many believe that the moon cycles impact our emotions and energy. Let’s explore the science and myths.',
    category: 'Science',
    author: 'Admin',
    likes: 653,
    comments: 88,
    date: '2025-08-21',
    tags: ['Lunar', 'Health'],
  },
  {
    id: 5,
    url: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=80',
    header: 'Morning Yoga Routines to Start Your Day Right',
    text: 'Improve your focus, flexibility, and peace of mind with these energizing morning yoga flows.',
    category: 'Fitness',
    author: 'Admin',
    likes: 987,
    comments: 165,
    date: '2025-08-20',
    tags: ['Fitness', 'Routine'],
  },
  {
    id: 6,
    url: 'https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?auto=format&fit=crop&w=800&q=80',
    header: 'Crystal Healing: What You Need to Know',
    text: 'Curious about crystal healing? Here’s a beginner’s guide to popular stones and how they’re used.',
    category: 'Healing',
    author: 'Admin',
    likes: 541,
    comments: 72,
    date: '2025-08-18',
    tags: ['Healing', 'Crystals'],
  },
  {
    id: 7,
    url: 'https://images.unsplash.com/photo-1549122728-f519709caa9c?auto=format&fit=crop&w=800&q=80',
    header: 'A Beginner’s Guide to Reading Tarot Cards',
    text: 'Step into the mystical world of tarot and learn the meanings behind popular cards and spreads.',
    category: 'Spirituality',
    author: 'Admin',
    likes: 1203,
    comments: 211,
    date: '2025-08-15',
    tags: ['Tarot', 'Spirituality'],
  },
  {
    id: 8,
    url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
    header: 'The Astrology of 2025: Big Shifts Ahead',
    text: '2025 brings major planetary shifts. Here’s what to expect for each zodiac sign.',
    category: 'Forecast',
    author: 'Admin',
    likes: 1001,
    comments: 194,
    date: '2025-08-10',
    tags: ['Forecast', 'Zodiac'],
  },
  {
    id: 9,
    url: 'https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?auto=format&fit=crop&w=800&q=80',
    header: 'The Power of Journaling for Mental Clarity',
    text: 'Explore how daily journaling can reduce stress, boost creativity, and bring emotional balance.',
    category: 'Mindfulness',
    author: 'Admin',
    likes: 712,
    comments: 134,
    date: '2025-08-05',
    tags: ['Mindfulness', 'Mental Health'],
  },
  {
    id: 10,
    url: 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=800&q=80',
    header: 'Daily Affirmations to Boost Your Vibration',
    text: 'Positive affirmations can reset your mindset. Try these daily mantras for a better you.',
    category: 'Affirmations',
    author: 'Admin',
    likes: 898,
    comments: 176,
    date: '2025-08-01',
    tags: ['Affirmations', 'Positivity'],
  }
];

export default blogData;
